development:
  adapter: postgresql
  host: localhost
  database: testapp_development
  username: postgres
  password: vivek
test:
  adapter: postgresql
  host: localhost
  database: testapp_test
  username: postgres
  password: vivek
